namespace EBikeManager.Application.Models.Dtos;

public sealed record RideDetailDto(
    string Id,
    string? Title,
    string? BikeName,
    string? BikeModel,
    DateTime LocalStartTime,
    double? DistanceMeters,
    double? MovingSeconds,
    double? ElapsedSeconds,
    double? AverageSpeedKmh,
    double? MaximumSpeedKmh,
    double? AverageCadence,
    double? MaximumCadence,
    double? AverageRiderPowerWatts,
    double? MaximumRiderPowerWatts,
    double? AverageHeartRate,
    double? MaximumHeartRate,
    double? ElevationGainMeters,
    double? ElevationLossMeters,
    double? CaloriesKcal,
    double? RiderEnergySharePercent,
    double? Co2Grams,
    double? Co2CarGrams,
    int? AbsInterventions,
    IReadOnlyList<AssistModeShareDto> AssistModes,
    bool HasFit,
    bool HasGpx,
    RideTrackDto? Track,
    string? TrackProblem,
    IReadOnlyList<RideExportDto>? Exports = null);
