// <auto-generated />
using System;
using EBikeManager.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EBikeManager.Application.Data.Migrations
{
    [DbContext(typeof(EBikeManagerDbContext))]
    [Migration("20260930131451_AddBikeDetails")]
    partial class AddBikeDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("EBikeManager.Application.Models.Entities.Bike", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("addedAt");

                    b.Property<DateTime?>("DetailsUpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("detailsUpdatedAt");

                    b.Property<bool?>("HasFlowPlus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hasFlowPlus");

                    b.Property<string>("LocationJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("locationJson");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PassJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("passJson");

                    b.Property<string>("ProfileJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("profileJson");

                    b.Property<string>("StateOfChargeJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("stateOfChargeJson");

                    b.HasKey("Id");

                    b.ToTable("bikes", (string)null);
                });

            modelBuilder.Entity("EBikeManager.Application.Models.Entities.ConfigEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("config", (string)null);
                });

            modelBuilder.Entity("EBikeManager.Application.Models.Entities.Ride", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double?>("AverageRiderPowerWatts")
                        .HasColumnType("REAL")
                        .HasColumnName("averageRiderPowerWatts");

                    b.Property<double?>("AverageSpeedKmh")
                        .HasColumnType("REAL")
                        .HasColumnName("averageSpeedKmh");

                    b.Property<string>("BikeId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("bikeId");

                    b.Property<double?>("CaloriesKcal")
                        .HasColumnType("REAL")
                        .HasColumnName("caloriesKcal");

                    b.Property<int?>("DistanceMeters")
                        .HasColumnType("INTEGER")
                        .HasColumnName("distanceMeters");

                    b.Property<int?>("ElevationGainMeters")
                        .HasColumnType("INTEGER")
                        .HasColumnName("elevationGainMeters");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("endTime");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("firstSeenAt");

                    b.Property<int?>("FitAveragePowerWatts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fitAveragePowerWatts");

                    b.Property<double?>("FitDistanceMeters")
                        .HasColumnType("REAL")
                        .HasColumnName("fitDistanceMeters");

                    b.Property<DateTime?>("FitDownloadedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("fitDownloadedAt");

                    b.Property<string>("FitError")
                        .HasColumnType("TEXT")
                        .HasColumnName("fitError");

                    b.Property<bool?>("FitHasGps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fitHasGps");

                    b.Property<string>("FitPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("fitPath");

                    b.Property<string>("FitSha256")
                        .HasColumnType("TEXT")
                        .HasColumnName("fitSha256");

                    b.Property<long?>("FitSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fitSizeBytes");

                    b.Property<double?>("FitTimerSeconds")
                        .HasColumnType("REAL")
                        .HasColumnName("fitTimerSeconds");

                    b.Property<bool>("FitUnavailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("fitUnavailable");

                    b.Property<int?>("MovingSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("movingSeconds");

                    b.Property<int?>("RiderEnergySharePercent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("riderEnergySharePercent");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("startTime");

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}")
                        .HasColumnName("summaryJson");

                    b.Property<string>("TimeZone")
                        .HasColumnType("TEXT")
                        .HasColumnName("timeZone");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("StartTime");

                    b.ToTable("rides", (string)null);
                });

            modelBuilder.Entity("EBikeManager.Application.Models.Entities.SecretEntry", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Name");

                    b.ToTable("secrets", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
