// <auto-generated />
using System;
using EBikeManager.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EBikeManager.Application.Data.Migrations
{
    [DbContext(typeof(EBikeManagerDbContext))]
    [Migration("20261002114919_AddNotificationChannels")]
    partial class AddNotificationChannels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("EBikeManager.Application.Models.Entities.Bike", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("addedAt");

                    b.Property<DateTime?>("BridgeBatteryAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("bridgeBatteryAt");

                    b.Property<double?>("BridgeBatteryPercent")
                        .HasColumnType("REAL")
                        .HasColumnName("bridgeBatteryPercent");

                    b.Property<DateTime?>("BridgeOdometerAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("bridgeOdometerAt");

                    b.Property<double?>("BridgeOdometerKm")
                        .HasColumnType("REAL")
                        .HasColumnName("bridgeOdometerKm");

                    b.Property<DateTime?>("DetailsUpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("detailsUpdatedAt");

                    b.Property<bool?>("HasFlowPlus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hasFlowPlus");

                    b.Property<string>("LocationJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("locationJson");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PassJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("passJson");

                    b.Property<string>("ProfileJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("profileJson");

                    b.Property<string>("StateOfChargeJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("stateOfChargeJson");

                    b.HasKey("Id");

                    b.ToTable("bikes", (string)null);
                });

            modelBuilder.Entity("EBikeManager.Application.Models.Entities.BikeDocument", b =>
                {
                    b.Property<string>("BikeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("bikeId");

                    b.Property<string>("FileId")
                        .HasColumnType("TEXT")
                        .HasColumnName("fileId");

                    b.Property<DateTime?>("AddedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("addedAt");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("contentType");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("fileType");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("savedAt");

                    b.Property<DateTime?>("SourceUpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("sourceUpdatedAt");

                    b.HasKey("BikeId", "FileId");

                    b.ToTable("bikeDocuments", (string)null);
                });

            modelBuilder.Entity("EBikeManager.Application.Models.Entities.BikePicture", b =>
                {
                    b.Property<string>("BikeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("bikeId");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("contentType");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("savedAt");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sourceUrl");

                    b.HasKey("BikeId");

                    b.ToTable("bikePictures", (string)null);
                });

            modelBuilder.Entity("EBikeManager.Application.Models.Entities.ConfigEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("config", (string)null);
                });

            modelBuilder.Entity("EBikeManager.Application.Models.Entities.NotificationChannel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("ActivityFailed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activityFailed");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("displayName");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("TEXT")
                        .HasColumnName("lastActivity");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("notificationChannels", (string)null);
                });

            modelBuilder.Entity("EBikeManager.Application.Models.Entities.Ride", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<double?>("AverageRiderPowerWatts")
                        .HasColumnType("REAL")
                        .HasColumnName("averageRiderPowerWatts");

                    b.Property<double?>("AverageSpeedKmh")
                        .HasColumnType("REAL")
                        .HasColumnName("averageSpeedKmh");

                    b.Property<string>("BikeId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("bikeId");

                    b.Property<string>("BikeModel")
                        .HasColumnType("TEXT")
                        .HasColumnName("bikeModel");

                    b.Property<string>("BikeName")
                        .HasColumnType("TEXT")
                        .HasColumnName("bikeName");

                    b.Property<double?>("CaloriesKcal")
                        .HasColumnType("REAL")
                        .HasColumnName("caloriesKcal");

                    b.Property<int?>("DistanceMeters")
                        .HasColumnType("INTEGER")
                        .HasColumnName("distanceMeters");

                    b.Property<int?>("ElevationGainMeters")
                        .HasColumnType("INTEGER")
                        .HasColumnName("elevationGainMeters");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("endTime");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("firstSeenAt");

                    b.Property<int?>("FitAveragePowerWatts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fitAveragePowerWatts");

                    b.Property<double?>("FitDistanceMeters")
                        .HasColumnType("REAL")
                        .HasColumnName("fitDistanceMeters");

                    b.Property<DateTime?>("FitDownloadedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("fitDownloadedAt");

                    b.Property<string>("FitError")
                        .HasColumnType("TEXT")
                        .HasColumnName("fitError");

                    b.Property<bool?>("FitHasGps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fitHasGps");

                    b.Property<string>("FitPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("fitPath");

                    b.Property<string>("FitSha256")
                        .HasColumnType("TEXT")
                        .HasColumnName("fitSha256");

                    b.Property<long?>("FitSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fitSizeBytes");

                    b.Property<double?>("FitTimerSeconds")
                        .HasColumnType("REAL")
                        .HasColumnName("fitTimerSeconds");

                    b.Property<bool>("FitUnavailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("fitUnavailable");

                    b.Property<DateTime?>("GpxDownloadedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("gpxDownloadedAt");

                    b.Property<string>("GpxPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("gpxPath");

                    b.Property<bool>("GpxUnavailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("gpxUnavailable");

                    b.Property<int?>("MovingSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("movingSeconds");

                    b.Property<int?>("RiderEnergySharePercent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("riderEnergySharePercent");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("startTime");

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("{}")
                        .HasColumnName("summaryJson");

                    b.Property<string>("TimeZone")
                        .HasColumnType("TEXT")
                        .HasColumnName("timeZone");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("StartTime");

                    b.ToTable("rides", (string)null);
                });

            modelBuilder.Entity("EBikeManager.Application.Models.Entities.RideExport", b =>
                {
                    b.Property<string>("RideId")
                        .HasColumnType("TEXT")
                        .HasColumnName("rideId");

                    b.Property<string>("Integration")
                        .HasColumnType("TEXT")
                        .HasColumnName("integration");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempts");

                    b.Property<DateTime?>("ExportedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("exportedAt");

                    b.Property<DateTime>("LastAttemptAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("lastAttemptAt");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<string>("Problem")
                        .HasColumnType("TEXT")
                        .HasColumnName("problem");

                    b.Property<string>("RemoteId")
                        .HasColumnType("TEXT")
                        .HasColumnName("remoteId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("RideId", "Integration");

                    b.ToTable("rideExports", (string)null);
                });

            modelBuilder.Entity("EBikeManager.Application.Models.Entities.SecretEntry", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Name");

                    b.ToTable("secrets", (string)null);
                });

            modelBuilder.Entity("EBikeManager.Application.Models.Entities.BikeDocument", b =>
                {
                    b.HasOne("EBikeManager.Application.Models.Entities.Bike", null)
                        .WithMany()
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EBikeManager.Application.Models.Entities.BikePicture", b =>
                {
                    b.HasOne("EBikeManager.Application.Models.Entities.Bike", null)
                        .WithOne()
                        .HasForeignKey("EBikeManager.Application.Models.Entities.BikePicture", "BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EBikeManager.Application.Models.Entities.RideExport", b =>
                {
                    b.HasOne("EBikeManager.Application.Models.Entities.Ride", null)
                        .WithMany()
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
