<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.assert" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Samples\bike.png" LogicalName="EBikeManager.TestSupport.Samples.bike.png" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EBikeManager.UnitTests" />
    <InternalsVisibleTo Include="EBikeManager.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EBikeManager.Application\EBikeManager.Application.csproj" />
  </ItemGroup>

</Project>
